### PR TITLE
Itpartners tomasz patch 1

### PR DESCRIPTION
**Pull request by itpartners-tomasz**
Changes in domain name

### CODE REVIEW

**Comment by itpartners-tomasz** [comment]
First marge - domain names change

**Comment by PiotrMachowski** [comment]
You _might_ want to change your credentials now

**Comment by itpartners-tomasz** [comment]
> You _might_ want to change your credentials now

Adequate price for stupidity, could your delete this request...

Just not to put trash into your repo....

i am trying to do similar thing as you, but using mobile eLicznika API

**Comment by itpartners-tomasz** [comment]
Only owner of repo can do it using virtual assistant:

Could you follow link:
https://support.github.com/request/remove-data

Chose remove pull request, then "single", as URL you should enter https://github.com/PiotrMachowski/Home-Assistant-custom-components-Tauron-AMIplus/pull/43

if it works I will buy you a beer ;) you know my email address already

**Comment by PiotrMachowski** [comment]
I have created a request, now we have to wait

**Pull request closed without merging**
