### PR TITLE
fix the SSLError

### PR DESCRIPTION
**Pull request by araczkowski**
fix for #1 

:+1:

### CODE REVIEW

**Comment by araczkowski** [comment]
config flow, have fun :)

image

image

image

**Review by PiotrMachowski — COMMENTED** [review]
@araczkowski I have removed some AIS leftovers, are you ok with these changes?

**Comment by araczkowski** [comment]
Yes sure. It is your code, fell free to change anything you wish.

Pozdrowienia, Miłego dnia Piotr!

wt., 23 mar 2021, 21:06 użytkownik Piotr Machowski ***@***.***>
napisał:

**Comment by PiotrMachowski** [comment]
@araczkowski thank you again! 👍 

Pozdrawiam! :)

**Comment by araczkowski** [comment]
You are very Welcome Piotr ;) Remember...

Trzymaj się!

BTW
you can add the graphic for your integration here:
https://github.com/home-assistant/brands

**Comment by PiotrMachowski** [comment]
I remember, but this is a bit more complex topic... We can talk a bit more privately [here](https://ai-speaker.discourse.group/u/3.14)

I know, I will add it :)

**Pull request merged**
